title: Alexander Stevens
description: Machine Learning Engineer at ML6 | PhD in Trustworthy AI | Passionate about building explainable and impactful AI solutions
github_username: AlexanderPaulStevens
email: alexander.stevens@telenet.be
logo: /assets/pasfoto.jpg
theme: jekyll-theme-minimal

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/AlexanderPaulStevens" }

# Set this to true to get LaTeX math equation support
use_math: true

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: true

# Set this to true to display image previews on home page, if they exist
show_image: true

# Set this to true to display tags on each post
show_tags: true

# this setting allows you to keep pages organized in the _pages folder
include:
  - _pages

# This specifies what badges are turned on by default for notebook posts.
default_badges:
  github: true
  
